version: "3.8"

services:
  my_app:
      ports:
        - ${PORT}:${PORT}
      build:
        context: ./
        dockerfile: Dockerfile.dev
        args:
          NEXT_PORT: ${PORT}
          NEXT_PUBLIC_GOOGLE_KEY: ${GOOGLE_KEY}
          NEXT_PUBLIC_APP_VERSION: ${NEXT_APP_VERSION}
      environment:
        - API_URL=${API_URL}
        - GOOGLE_KEY=${GOOGLE_KEY}
      volumes:
        - ./:/usr/src/app
        - /usr/src/app/node_modules
        - /usr/src/app/.next
        

#   nginx-dev:
#     build:
#       context: ./nginx
#       # dockerfile: ./nginx/Dockerfile
#     # volumes:
#     #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#     #   - ./nginx/conf.d:/etc/nginx/conf.d
#     ports:
#       - "3001:3001"
#     depends_on:
#       - frontend
#     restart: always

# volumes:
#   nextjs-dev-node_modules:
#   nextjs-dev-next: