FROM node:12

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Installing dependencies
COPY package*.json .
COPY yarn.lock .
RUN yarn install

# Copying source files
COPY . .

ARG NEXT_PORT
ENV NEXT_PORT=${NEXT_PORT}

# Building app
ENV PORT=${NEXT_PORT}
RUN yarn build
EXPOSE ${NEXT_PORT}



# Running the app
CMD ["yarn", "dev"]