version: "3.8"

services:
  nextjs:
    image: swadesh:${NEXT_APP_VERSION}
    ports:
      - "3000:3000"
    build:
      context: ./
      dockerfile: Dockerfile
      target: prod
      args:
        NEXT_PUBLIC_GOOGLE_KEY: ${GOOGLE_KEY}
        NEXT_PUBLIC_APP_VERSION: ${NEXT_APP_VERSION}
    volumes:
      - /app/node_modules
      - /app/.next
    restart: always
    environment:
      - API_URL=${API_URL}
      - GOOGLE_KEY=${GOOGLE_KEY}
  nginx:
    build: ./nginx
    ports:
      - 3001:3001
